name: Under Palm Trees
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2783a8'
    - '#67a5bc'
    - '#bcc9d2'
    - '#1d3132'
    - '#afa697'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
