name: Under Palm Trees
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17288646358065307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090708'
    - '#bcdebc'
    - '#f36b51'
    - '#f99c5a'
    - '#505d54'
  brandStrength: 0.5397123156581074
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
