name: Under Palm Trees
favicon: null
layout_spectrum: 0.5829149791970849
typography_spectrum: 0.17288646358065307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#252525'
    - '#000000'
    - '#b4c5b7'
    - '#626613'
  brandStrength: 0.5397123156581074
  lightness: 0.5479169928003103
  saturation: 0.5421049110591412
  rhythmicContrast: 0.00953105022199452
purpose: []
