name: Under Palm Trees
favicon: null
layout_spectrum: 0.2060932
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#252525'
    - '#000000'
    - '#b4c5b7'
    - '#626613'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
